@startuml iron-age
skinparam shadowing false
skinparam ComponentBorderColor black
skinparam ArrowColor black
skinparam ActorBorderColor black

!include <tupadr3/common>

!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Concepts/firewall_orange>
!include <office/Clouds/cloud_disaster_red>


actor "Developer" as dev

OFF_DATABASE_SERVER(db, "Tom")
OFF_APPLICATION_SERVER(app, "Jerry")

dev -> db
dev --> app

@enduml