@startuml lb2fargate
title Building a AWS Load Balancer

top to bottom direction

skinparam dpi 300
skinparam shadowing false
skinparam monochrome false
skinparam componentStyle uml2
skinparam packageStyle rectangle
skinparam packageTitleAlignment left

Person user

package "AWS" {
    frame "Elastic Load Balancing" {
        [Target Group] as tg
    }

    frame "Application Scaling Group" {
        [Application Scaling Group] as asg
        [Fargate Instances] as fargate

        asg -> fargate : launches instances
    }
}

asg -[hidden]d- fargate

tg -[bold,#red]> fargate : sends traffic to instances

@enduml
