ensure_path( 'TEXINPUTS', '../../../../tex//' );
ensure_path( 'BIBINPUTS', '../../../../references//' );

@default_files = ('main.tex');

# PDF configuration
$pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape';

$out_dir = 'out';
$pdf_mode = 1;