@startuml lb2
title Building a AWS Load Balancer

top to bottom direction

skinparam dpi 300
skinparam shadowing false
skinparam monochrome false
skinparam componentStyle uml2
skinparam packageStyle rectangle
skinparam packageTitleAlignment left

Person user

package "AWS" {
    frame "Elastic Load Balancing" {
        [Target Group] as tg
    }

    frame "Auto Scaling Group" {
        [Auto Scaling Group] as asg
        [EC2 Instances] as ec2

        asg -> ec2 : launches instances
    }
}

asg -[hidden]d- ec2

tg -[bold,#red]> ec2 : sends traffic to instances

@enduml
