ensure_path( 'TEXINPUTS', '../../tex//' );
$bibtex = "bibtex -include-directory=../../references %O %B";

@default_files = ('main.tex');

$pdflatex = 'pdflatex -synctex=1 -interaction=nonstopmode';
$out_dir = 'out';

$pdf_mode = 1;
