ensure_path( 'TEXINPUTS', '../../tex//', '..', '../../slides/distributed2' );
ensure_path( 'BIBINPUTS', '../../references//', '../../../references//' );

@default_files = ('main.tex');

$pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape';
$out_dir = 'out';

$pdf_mode = 1;
