ensure_path( 'TEXINPUTS', '../../tex//', '..' );
ensure_path( 'BIBINPUTS', '../../references//', '../../../references//' );

@default_files = ('main.tex');

$pre_tex_code = '\AtBeginDocument{\teachermodetrue}';

$pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape';
$out_dir = 'out';

$pdf_mode = 1;
