@startuml dropRecover
skinparam shadowing false
skinparam ParticipantBorderColor black
skinparam ArrowColor black
skinparam ParticipantBackgroundColor white
skinparam ParticipantFontColor black
skinparam SequenceLifeLineBorderColor black

autonumber
WebClient ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient -> CartService : HTTP POST api.sahara.com/v1/cart
CartService -> Database : Update cart
CartService -> WebClient : HTTP Response 200

@enduml