@startuml dropRecoverDos
!pragma teoz true

skinparam shadowing false
skinparam ParticipantBorderColor black
skinparam ArrowColor black
skinparam ParticipantBackgroundColor white
skinparam ParticipantFontColor black
skinparam SequenceLifeLineBorderColor black

participant WebClientN
participant WebClient1
participant CartService
participant WebClient2
participant WebClient3

autonumber
WebClient1 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient2 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient1 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient2 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient3 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient1 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient2 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient3 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient1 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient2 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClient3 ->x CartService : HTTP POST api.sahara.com/v1/cart
WebClientN ->x CartService : HTTP POST api.sahara.com/v1/cart

WebClient1 -> CartService : HTTP POST api.sahara.com/v1/cart
& WebClient2 -> CartService : HTTP POST api.sahara.com/v1/cart
WebClient3 -> CartService : HTTP POST api.sahara.com/v1/cart
& WebClientN -> CartService : HTTP POST api.sahara.com/v1/cart


@enduml