@startuml drop2Fix
skinparam shadowing false
skinparam ParticipantBorderColor black
skinparam ArrowColor black
skinparam ParticipantBackgroundColor white
skinparam ParticipantFontColor black
skinparam SequenceLifeLineBorderColor black

autonumber
WebClient -> CartService : HTTP POST api.sahara.com/v1/cart
note left: Token: 1234
CartService -> Database : Update cart
CartService ->x WebClient : HTTP Response 200
WebClient -> CartService : HTTP POST api.sahara.com/v1/cart
note left: Token: 1234
CartService ->x WebClient : HTTP Response 409

@enduml