@startuml Async

' left to right direction

skinparam shadowing false
skinparam ParticipantBorderColor black
skinparam ArrowColor black
skinparam ParticipantBackgroundColor white
skinparam ParticipantFontColor black
skinparam SequenceLifeLineBorderColor black

autonumber

participant ProductBrowsing
database Leader #ccfddd
database Follower1 #ccfddd
' database Follower2 #ccfddd

ProductBrowsing -> Leader : UPDATE products SET stock=4
Leader -> Follower1 : UPDATE
Leader -> ProductBrowsing : OK
Follower1 -> Leader : OK

@enduml