@startuml view-concept
!theme sketchy-outline
skinparam shadowing false
skinparam NodeBorderColor black
skinparam ArrowColor black
skinparam NodeBackgroundColor transparent
skinparam NodeFontColor black


"interesting software" -> [illustrated by] "views"
"views" -> [slice of] "interesting software"
"views" --> "view model"
"view model" --> "4+1 views"
"4+1 views" --> "logical"
"4+1 views" --> "process"
"4+1 views" --> "development"
"4+1 views" --> "physical"
"4+1 views" --> "scenario"
"view model" -> "software architecture in practice"
"software architecture in practice" --> "module"
"software architecture in practice" --> "component-and-connector"
"software architecture in practice" --> "allocation"
"view model" -> "C4 model"

"views" -> "view notations"
"view notations" -> "UML"
"UML" --> "deployment diagram"
"UML" --> "component diagram"
"UML" --> "sequence diagram"
"UML" --> "class diagram"

"view notations" --> "C4 model"

"C4 model" --> "context"
"C4 model" --> "containers"
"C4 model" --> "components"
"C4 model" --> "code"

"view notations" -> [drawn by] "modelling tools"

"interesting software" --> [design influenced by] "architecturally significant requirements"
@enduml