ensure_path( 'TEXINPUTS', '../tex//', 'views', 'layered', 'microkernel', 'security', 'pipeline', 'service-based', '../slides/distributed2' );
ensure_path( 'BIBINPUTS', '../references//:../../references//' );

@default_files = ('notes.tex');

$pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape';
$out_dir = 'out';

$pdf_mode = 1;
