ensure_path( 'TEXINPUTS', '../tex//' );
ensure_path( 'BIBINPUTS', '../references//' );

@default_files = ('notes.tex');

$pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape';
$out_dir = 'out';

$pdf_mode = 1;
