ensure_path( 'TEXINPUTS', '../../tex//' );
ensure_path( 'TEXINPUTS', '..' );
ensure_path( 'BIBINPUTS', '../../references//' );
ensure_path( 'BIBINPUTS', '../../../references//' );

@default_files = ('main.tex');

$pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape';
$out_dir = 'out';

$pdf_mode = 1;
