@startuml cloud-age
skinparam shadowing false
skinparam ComponentBorderColor black
skinparam ArrowColor black
skinparam ActorBorderColor black

!include <tupadr3/common>

!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Concepts/firewall_orange>
!include <office/Clouds/cloud_disaster_red>


actor "Developer" as dev

cloud {
collections c [
{{
    database {

    }
}}
]
collections d [
{{
    queue {

    }
}}
]
collections f [
{{
    node {

    }
}}
]
}

' cloud foo2
' collections OFF_DATABASE_SERVER(db2, "Tom")

dev -> c
dev -> c
dev -> c
dev -> c
dev -> c
dev -> c
dev -> c
dev -> c
dev -> c
dev -> c

dev -> d
dev -> d
dev -> d
dev -> d
dev -> d
dev -> d
dev -> d
dev -> d
dev -> d

dev -> f
dev -> f
dev -> f
dev -> f
dev -> f
dev -> f
dev -> f
dev -> f
dev -> f

c <-> f
d <-> c


@enduml