@startuml Context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddContainerTag("browser", $bgColor="#bcddfc", $fontColor="#000000")
AddContainerTag("database", $bgColor="#ccfddd", $fontColor="#000000", $borderColor="#cccccc")

skinparam roundcorner 20
skinparam Padding 20

UpdateElementStyle(node, $borderColor="#cccccc", $fontColor="#5c5c5c")
UpdateElementStyle(container, $bgColor="#5388cb")

hide stereotype

Person(user, "Coffee Shop Customer")
Person(supplier, "Beans Supplier")

System_Boundary(system, "Coffee Shop", "") {
    Container(beans, "Beans Service", "")
}

Rel(user, system, "Order coffee")
Rel(supplier, beans, "Supply beans")

@enduml