name: Build Case Studies

on:
  workflow_dispatch:
  push:
    paths:
      - studies/**

jobs:
  build-studies:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Disable git owner warning
        run: git config --global safe.directory '*'

      - name: Correct last modified
        run: ./.github/workflows/set-last-updated.sh

      - name: Compile studies
        run: ./bin/build_studies.sh

      - name: Upload case studies
        uses: actions/upload-artifact@v4
        with:
          name: studies
          path: |
            ./dist/**/*
  
