name: Build OpenAPI Docs

on:
  workflow_dispatch:
  push:
    paths:
      - practicals/button/spec.yml
      - studies/chatterbox/spec.yml
      - studies/spamoverflow/spec.yml
      - studies/ticketoverflow/spec.yml

jobs:
  build-api-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Button API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html2
          openapi-file: ./practicals/button/spec.yml
          command-args: --output ./dist/api/button --template-dir ./assessment/cloud/docs-template

      - name: Generate Chatterbox API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html2
          openapi-file: ./studies/chatterbox/spec.yml
          command-args: --output ./dist/api/chatterbox --template-dir ./assessment/cloud/docs-template

      - name: Generate SpamOverflow API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html2
          openapi-file: ./studies/spamoverflow/spec.yml
          command-args: --output ./dist/api/spamoverflow --template-dir ./assessment/cloud/docs-template

      - name: Generate TicketOverflow API
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html2
          openapi-file: ./studies/ticketoverflow/spec.yml
          command-args: --output ./dist/api/ticketoverflow --template-dir ./assessment/cloud/docs-template

      - name: Upload APIs
        uses: actions/upload-artifact@v4
        with:
          name: apis
          path: |
            ./dist/api/**

